from src.manifolds import Manifold
from src.manifolds.euclidean import Euclidean

class DeformedGaussianPullbackManifold(Manifold): # TODO
    """ Base class describing a R^d under a l^2-pullback Riemannian geometry generated by a DeformedGaussian unimodal distribution """

    def __init__(self, deformed_gaussian):
        super().__init__(deformed_gaussian.d)
        self.dg = deformed_gaussian # unimodal distribution
        self.manifold = Euclidean(self.d)

    def barycentre(self, x):
        """

        :param x: N x d
        :return: d
        """
        return self.dg.phi.inverse(self.manifold.barycentre(self.dg.phi(x)))

    def inner(self, x, X, Y):
        """

        :param x: N x d
        :param X: N x M x d
        :param Y: N x L x d
        :return: N x M x L
        """
        return self.manifold.inner(self.dg.forward(x),
                                   self.dg.differential_forward(x, X),
                                   self.dg.differential_forward(x, Y)
                                   )
    
    def geodesic(self, x, y, t):
        """

        :param x: d
        :param y: d
        :param t: N
        :return: N x d
        """
        return self.dg.phi.inverse(self.manifold.geodesic(self.dg.phi.forward(x), self.dg.phi.forward(y), t))

    def log(self, x, y):
        """

        :param x: d
        :param y: N x d
        :return: N x d
        """
        return self.dg.phi.differential_inverse(self.dg.phi.forward(x),
                                                self.manifold.log(self.dg.phi.forward(x), self.dg.phi.forward(y))
                                                )

    def exp(self, x, X):
        """

        :param x: d
        :param X: N x d
        :return: N x d
        """
        return self.dg.phi.inverse(self.manifold.exp(self.dg.phi.forward(x), self.dg.phi.differential_forward(x, X)))
    
    def distance(self, x, y):
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L
        """
        return self.manifold.distance(self.dg.forward(x), self.dg.forward(y))

    def parallel_transport(self, x, X, y):
        """

        :param x: d
        :param X: N x d
        :param y: d
        :return: N x d
        """
        return self.dg.phi.differential_inverse(self.dg.phi.forward(y),
                                                self.manifold.parallel_transport(self.dg.phi.forward(x),
                                                                                 self.dg.phi.differential_forward(x, X),
                                                                                 self.dg.phi.forward(y)
                                                                                 )
                                                )