from src.manifolds import Manifold
from src.manifolds.deformed_sum_of_gaussian_pullback_manifold import DeformedSumOfGaussianPullbackManifold

import torch

class DeformedSumOfIdenticalGaussianPullbackManifold(DeformedSumOfGaussianPullbackManifold): # TODO check input discrepancies between manifold mapping input and diffeomorphism input. Latter always assumes batch dimension
    """ Base class describing a R^d under a sum of identical Gaussian-pullback Riemannian geometry generated by a DeformedSumofIdenticalGaussian multimodal distribution """

    def __init__(self, deformed_sum_of_gaussian): 
        super().__init__(deformed_sum_of_gaussian, L=0, L2=0)
