from src.manifolds import Manifold
from src.manifolds.discrete_time_manifolds.sum_of_gaussian.sum_of_diagonal import SumOfDiagonal

import torch

class DeformedSumOfGaussianPullbackManifold(Manifold): # TODO check input discrepancies between manifold mapping input and diffeomorphism input. Latter always assumes batch dimension
    """ Base class describing a R^d under a sum of Gaussian-pullback Riemannian geometry generated by a DeformedSumofGaussian multimodal distribution """

    def __init__(self, deformed_sum_of_gaussian):
        super().__init__(deformed_sum_of_gaussian.d)
        self.dsg = deformed_sum_of_gaussian # multimodal distribution
        self.manifold = SumOfDiagonal(self.d, deformed_sum_of_gaussian.psi, deformed_sum_of_gaussian.weights)

    def ricci_scalar(self, x):
        """
        R
        :param x: N x d
        :return: N 
        """
        return self.manifold.ricci_scalar(self.dsg.phi(x))

    def barycentre(self, x):
        """

        :param x: N x d
        :return: d
        """
        return self.dsg.phi.inverse(self.manifold.barycentre(self.dsg.phi(x))[None])[0]

    def inner(self, x, X, Y):
        """

        :param x: N x d
        :param X: N x M x d
        :param Y: N x L x d
        :return: N x M x L
        """
        _, M, _ = X.shape
        _, L, _ = Y.shape
        return self.manifold.inner(self.dsg.phi.forward(x),
                                   self.dsg.phi.differential_forward((x[:,None] * torch.ones(M)[None,:,None]).reshape(-1,self.d), X.reshape(-1,self.d)).reshape(X.shape),
                                   self.dsg.phi.differential_forward((x[:,None] * torch.ones(L)[None,:,None]).reshape(-1,self.d), Y.reshape(-1,self.d)).reshape(Y.shape)
                                   )
    
    def geodesic(self, x, y, t, L=100, tol=1e-2, max_iter=20000, step_size=1/8):
        """

        :param x: d
        :param y: d
        :param t: N
        :return: N x d
        """
        return self.dsg.phi.inverse(self.manifold.geodesic(self.dsg.phi.forward(x[None])[0], self.dsg.phi.forward(y[None])[0], t, L=L, tol=tol, max_iter=max_iter, step_size=step_size))

    def log(self, x, y, L=100, tol=1e-2, max_iter=20000, step_size=1/8):
        """

        :param x: d
        :param y: N x d
        :return: N x d
        """
        N, _ = y.shape
        return self.dsg.phi.differential_inverse(self.dsg.phi.forward(x[None]) * torch.ones(N)[:,None],
                                                self.manifold.log(self.dsg.phi.forward(x[None])[0], self.dsg.phi.forward(y), L=L, tol=tol, max_iter=max_iter, step_size=step_size)
                                                )

    def exp(self, x, X, L=100, tol=1e-2, max_iter=20000):
        """

        :param x: d
        :param X: N x d
        :return: N x d
        """
        # if p is None:
        #     p = self.p
        N, _ = X.shape
        return self.dsg.phi.inverse(self.manifold.exp(self.dsg.phi.forward(x[None])[0], self.dsg.phi.differential_forward(x[None] * torch.ones(N)[:,None], X), L=L, tol=tol, max_iter=max_iter))
    
    def distance(self, x, y, L=100, tol=1e-2, max_iter=20000, step_size=1/8):
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L
        """
        return self.manifold.distance(self.dsg.forward(x.reshape(-1,self.d)).reshape(x.shape), self.dsg.forward(y.reshape(-1,self.d)).reshape(y.shape), L=L, tol=tol, max_iter=max_iter, step_size=step_size)

    def parallel_transport(self, x, X, y, L=100, tol=1e-2, max_iter=20000, step_size=1/8):
        """

        :param x: d
        :param X: N x d
        :param y: d
        :return: N x d
        """
        N, _ = X.shape
        return self.dsg.phi.differential_inverse(self.dsg.phi.forward(y[None]) * torch.ones(N)[:,None],
                                                self.manifold.parallel_transport(self.dsg.phi.forward(x[None])[0],
                                                                                 self.dsg.phi.differential_forward(x[None] * torch.ones(N)[:,None], X),
                                                                                 self.dsg.phi.forward(y[None])[0]
                                                                                 ), L=L, tol=tol, max_iter=max_iter, step_size=step_size
                                                )